apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      releaseName: loki-stack
      values: |
        loki:
          enabled: true
          persistence:
            enabled: false
          config:
            limits_config:
              retention_period: 168h
        promtail:
          enabled: true
        grafana:
          enabled: true
          adminPassword: "changeme123!"
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - grafana.kosar.sk
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.kosar.sk
          persistence:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true