apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 4.21.2
    helm:
      releaseName: falco
      values: |
        driver:
          kind: modern_ebpf
        falco:
          json_output: true
          json_include_output_property: true
          json_include_message_property: true
          http_output:
            enabled: true
            url: http://falco-falcosidekick:2801
        customRules:
          falco_rules.local.yaml: |-
            - macro: k8s_api_allowed_processes
              condition: >
                proc.name in (python, system-upgrade-, fleetcontroller, manager,
                              argocd-server, argocd-applicat, cainjector, webhook,
                              kyverno-plugin, policyreporter, local-path-prov,
                              fleet-agent, gitjob, helmops)

            - rule: Contact K8S API Server From Container
              condition: k8s_api_server and not k8s_api_allowed_processes
              output: >
                Unexpected connection to K8s API Server from container
                (connection=%fd.name process=%proc.name
                ns=%k8s.ns.name pod=%k8s.pod.name)
              priority: WARNING
              override:
                condition: replace
                output: replace
                priority: replace
        falcosidekick:
          enabled: true
          config:
            loki:
              hostport: http://loki-stack.monitoring.svc.cluster.local:3100
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true