apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 4.21.2
    helm:
      releaseName: falco
      values: |
        driver:
          kind: modern_ebpf
        falco:
          json_output: true
          json_include_output_property: true
          json_include_message_property: true
        falcosidekick:
          enabled: true
          config:
            loki:
              hostport: http://loki-stack.monitoring.svc.cluster.local:3100
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true