apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:xkosarf/k3s-gitops-argo.git
    targetRevision: main
    path: clusters/k3s-hetzner
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
