apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-website
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/xkosarf/k3s-gitops-argo.git
    targetRevision: main
    path: apps/lab-website
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-website
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true