apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.2.0
    helm:
      values: |
        ingressClass:
          enabled: true
          isDefaultClass: true
        ports:
          web:
            redirectToPort:
              name: websecure
        additionalArguments:
          - "--entrypoints.websecure.http.tls=true"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
