apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.5.10
    helm:
      valueFiles: []
      values: |
        server:
          service:
            type: ClusterIP
          ingress:
            enabled: false
        configs:
          cm:
            url: https://argocd.49.12.100.65.sslip.io
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
